"""Render SCIWEAVE.md — the generated, human- and AI-readable project map.

Regenerated on every commit(); never edit it by hand (edits are overwritten).
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from sciweave.schema import CATEGORIES, NODE_TYPES

if TYPE_CHECKING:
    from sciweave.project import Project


def _cell(s) -> str:
    return str(s if s is not None else "").replace("|", "\\|").replace("\n", " ")


def render_map(p: "Project") -> str:
    from sciweave.trace import edge_line

    g = p.graph
    status = p.status(check_disk=False)
    lines = [
        f"# {g['project']['name']} — SciWeave map",
        "",
        "> Generated by SciWeave from `.sciweave/graph.json`. Do not edit — run `sciweave` commands instead.",
        "> Dashboard: `sciweave serve` · provenance of one item: `sciweave trace <ID>`.",
        "",
    ]
    if g["project"].get("description"):
        lines += [g["project"]["description"], ""]
    n_nodes, n_edges = len(p.nodes), len(p.edges)
    stale = [nid for nid, s in status.items() if s["stale"]]
    lines += [f"**{n_nodes} nodes · {n_edges} links · {len(stale)} stale**", ""]
    if stale:
        lines += ["## Needs regeneration (stale)", ""]
        for nid in stale:
            lines.append(f"- **{nid}** · {p.nodes[nid]['label']} — {'; '.join(status[nid]['reasons'][:2])}")
        lines.append("")

    for cat in CATEGORIES:
        rows = [n for n in p.nodes.values() if NODE_TYPES[n["type"]]["category"] == cat]
        if not rows:
            continue
        lines += [f"## {cat.capitalize()}", "", "| ID | Label | Type | Mode | Path | Version | Final |", "|---|---|---|---|---|---|---|"]
        for n in sorted(rows, key=lambda x: (x["type"], x["id"])):
            lines.append(
                f"| {n['id']} | {_cell(n['label'])} | {n['type']} | {n['mode']} | `{_cell(n['path'] or '')}` | "
                f"{('v' + str(n['current_version'])) if n['current_version'] else '-'} | "
                f"{('v' + str(n['final_version'])) if n['final_version'] else ''} |"
            )
        lines.append("")

    if p.edges:
        lines += ["## Links (provenance)", "", "Red = carries result-changing parameters; green = none.", ""]
        for e in p.edges:
            lines.append(f"- `{e['id']}` {edge_line(p, e)}")
        lines.append("")

    if g["groups"]:
        lines += ["## Groups", ""]
        for name, meta in g["groups"].items():
            members = [n["id"] for n in p.nodes.values() if name in n["groups"]]
            lines.append(f"- **{meta.get('label') or name}**: {', '.join(members) or '(empty)'}")
        lines.append("")
    return "\n".join(lines)
