"""Render SCIWEAVE.md — the generated, human- and AI-readable project map.

Regenerated on every commit(); never edit it by hand (edits are overwritten).
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from sciweave.schema import CATEGORIES, NODE_TYPES

if TYPE_CHECKING:
    from sciweave.project import Project


def _cell(s) -> str:
    return str(s if s is not None else "").replace("|", "\\|").replace("\n", " ")


def render_map(p: "Project") -> str:
    from sciweave.trace import edge_line

    g = p.graph
    status = p.status(check_disk=False)
    lines = [
        f"# {g['project']['name']} — SciWeave map",
        "",
        "> Generated by SciWeave from `.sciweave/graph.json`. Do not edit — run `sciweave` commands instead.",
        "> Dashboard: `sciweave serve` · provenance of one item: `sciweave trace <ID>`.",
        "",
    ]
    if g["project"].get("description"):
        lines += [g["project"]["description"], ""]
    n_nodes, n_edges = len(p.nodes), len(p.edges)
    stale = [nid for nid, s in status.items() if s["stale"]]
    lines += [f"**{n_nodes} nodes · {n_edges} links · {len(stale)} stale**", ""]
    if stale:
        lines += ["## Needs regeneration (stale)", ""]
        for nid in stale:
            lines.append(f"- **{nid}** · {p.nodes[nid]['label']} — {'; '.join(status[nid]['reasons'][:2])}")
        lines.append("")

    if p.steps:
        summ = p.step_summary()
        lab = {k: v["label"] for k, v in p.steps.items()}
        lines += ["## Steps (analysis stages)", ""]
        for k, st in sorted(p.steps.items(), key=lambda kv: kv[1].get("order", 0)):
            s = summ.get(k, {"members": [], "within": 0, "in": {}, "out": {}})
            lines.append(f"### {st.get('order', '')}. {st['label']} (`{k}`)")
            if st.get("description"):
                lines.append(st["description"])
            lines.append(", ".join(f"{m} · {_cell(p.nodes[m]['label'])}" for m in sorted(s["members"])) or "(empty)")
            flow = [f"{s['within']} links within"]
            if s["in"]:
                flow.append("in from " + ", ".join(f"{lab.get(x, '(no step)')} ({n})" for x, n in s["in"].items()))
            if s["out"]:
                flow.append("out to " + ", ".join(f"{lab.get(x, '(no step)')} ({n})" for x, n in s["out"].items()))
            lines += ["", "*" + " · ".join(flow) + "*", ""]
        if None in summ:
            lines += [f"**No step yet:** {', '.join(sorted(summ[None]['members']))}", ""]

    for cat in CATEGORIES:
        rows = [n for n in p.nodes.values() if NODE_TYPES[n["type"]]["category"] == cat]
        if not rows:
            continue
        lines += [f"## {cat.capitalize()}", "", "| ID | Label | Type | Step | Mode | Path | Version | Final |",
                  "|---|---|---|---|---|---|---|---|"]
        for n in sorted(rows, key=lambda x: (x["type"], x["id"])):
            lines.append(
                f"| {n['id']} | {_cell(n['label'])} | {n['type']} | {n.get('step') or ''} | {n['mode']} | `{_cell(n['path'] or '')}` | "
                f"{('v' + str(n['current_version'])) if n['current_version'] else '-'} | "
                f"{('v' + str(n['final_version'])) if n['final_version'] else ''} |"
            )
        lines.append("")

    if p.edges:
        lines += ["## Links (provenance)", "", "Red = carries result-changing parameters; green = none.", ""]
        for e in p.edges:
            lines.append(f"- `{e['id']}` {edge_line(p, e)}")
        lines.append("")

    fams = {}
    for nid, n in p.nodes.items():
        if n.get("branch"):
            fams.setdefault(p.branch_family(nid)[0], None)
    if fams:
        lines += ["## Branches (alternative analyses)", ""]
        for root in fams:
            for x in p.branch_family(root):
                b = p.nodes[x].get("branch") or {}
                lines.append(f"- {'**' + x + '**' if b.get('status') == 'main' else x} · {_cell(p.nodes[x]['label'])} "
                             f"— {b.get('status', 'main')}" + (f" — why: {b['why']}" if b.get("why") else ""))
            lines.append("")

    recent = sorted(((v["ts"], nid, v) for nid, n in p.nodes.items() for v in n["versions"] if v.get("why")),
                    reverse=True)[:12]
    if recent:
        lines += ["## Recent updates and why", ""]
        for ts, nid, v in recent:
            lines.append(f"- {ts[:10]} **{nid}** v{v['v']}: {_cell(v.get('message', ''))} — why: {_cell(v['why'])}")
        lines.append("")

    if g["groups"]:
        lines += ["## Groups", ""]
        for name, meta in g["groups"].items():
            members = [n["id"] for n in p.nodes.values() if name in n["groups"]]
            lines.append(f"- **{meta.get('label') or name}**: {', '.join(members) or '(empty)'}")
        lines.append("")
    return "\n".join(lines)
